server:
  port: 8081
spring:
  application:
    name: transaction-processing
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction
    username: transaction
    password: transaction
  flyway:
    schemas:
      - public
      - s_transactions
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true