server:
  port: 8081
spring:
  application:
    name: transaction-processing
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: transaction
    password: transaction
  flyway:
    schemas:
      - public
      - s_transactions
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#        ddl-auto: update
#    properties:
#      hibernate:
#        show-sql: true
#        format_sql: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
